server:
  port: 8080

spring:
  data:
    mongodb:
      host:  service-mongodb
      port: 27021
      database: OtelKiralama
      username: bilgeUmit
      password: bilgeUmit*
  application:
    name: otelkiralama
  mail:
    username: gecekusumit@gmail.com
    password: jaquxzgbwqopyjhq #kontrol et
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


myapplication:
  redis:
    host: service-redis
